[tool.poetry]
name = "cumplo-spotter"
version = "0.3.4"
description = "A simple yet powerful API for spotting secure and high-return Cumplo investment opportunities"
authors = ["Cristobal Sfeir <cnsfeir@uc.cl>"]
packages = [{ include = "cumplo_spotter" }]

[tool.poetry.group.rest-api]
optional = true

[tool.poetry.group.rest-api.dependencies]
fastapi = "^0.109.1"
uvicorn = "^0.23.1"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.28.1"
arrow = "^1.2.3"
pydantic = "^2.1.1"
python-dotenv = "^1.0.0"
bs4 = "^0.0.1"
retry = "^0.9.2"
lxml = "^4.9.2"
google-cloud-logging = "^3.5.0"
cumplo-common = { version = "^0.6.8", source = "cumplo-pypi" }

[tool.poetry.dev-dependencies]
pylint = "^2.17.5"
flake8 = "^6.1.0"
black = "^23.7.0"
mypy = "^1.4.1"

[[tool.poetry.source]]
name = "cumplo-pypi"
url = "https://us-central1-python.pkg.dev/cumplo-scraper/cumplo-pypi/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
