[project]
name = "cumplo-spotter"
version = "1.2.1"
description = "A simple yet powerful API for spotting secure and high-return Cumplo investment opportunities"
authors = [{ name = "Cristobal Sfeir", email = "hello@cristobalsfeir.com" }]
packages = [{ include = "cumplo_spotter" }]

readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.28.1,<3.0.0",
    "arrow>=1.2.3,<2.0.0",
    "pydantic>=2.1.1,<3.0.0",
    "fastapi>=0.109.1,<0.110.0",
    "uvicorn>=0.23.1,<0.24.0",
    "gunicorn>=21.2.0,<22.0.0",
    "python-dotenv>=1.0.0,<2.0.0",
    "bs4>=0.0.1,<0.1.0",
    "retry>=0.9.2,<0.10.0",
    "lxml>=4.9.2,<5.0.0",
    "google-cloud-logging>=3.5.0,<4.0.0",
    "httpx>=0.26.0,<0.27.0",
]

[dependency-groups]
dev = ["mypy>=1.13.0", "ruff>=0.7.1"]

[[tool.mypy.overrides]]
module = [
    "requests.*",
    "pydantic.*",
    "psycopg2.*",
    "lxml.*",
    "babel.*",
    "bs4.*",
    "functions_framework.*",
    "firebase_admin.*",
    "retry.*",
    "starlette.*",
]
ignore_missing_imports = true
