[tool.poetry]
name = "cumplo-scraper"
version = "0.1.0"
description = "Cumplo scraper"
authors = ["Cristobal Sfeir <cnsfeir@uc.cl>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
arrow = "^1.2.3"
pydantic = "^1.10.2"
pylint = "^2.15.9"
python-dotenv = "^0.21.0"
Babel = "^2.11.0"
bs4 = "^0.0.1"
aiohttp = "^3.8.3"
asyncio = "^3.4.3"
functions-framework = "^3.3.0"
firebase-admin = "^6.0.1"
retry = "^0.9.2"

[tool.poetry.dev-dependencies]
Flask = "^2.2.2"
flake8 = "^5.0.4"
black = "^22.10.0"
mypy = "^0.991"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
